keywords_for_police = [
    "Misconduct",
    "Abuse of power",
    "Excessive force",
    "Discrimination",
    "Harassment",
    "Negligence",
    "Unprofessional behavior",
    "Violation of rights",
    "Brutality",
    "Racial profiling",
    "Corruption",
    "Unlawful arrest",
    "False imprisonment",
    "Use of tasers or firearms",
    "Unnecessary aggression",
    "Failure to respond",
    "Inappropriate conduct",
    "Intimidation",
    "Retaliation",
    "Failure to investigate",
    "Fabrication of evidence",
    "Violation of department policies",
    "Failure to provide assistance",
    "Lack of transparency",
    "Bias or prejudice",
    "Inadequate training",
    "Failure to identify oneself",
    "Unjustified search or seizure",
    "Ineffective communication",
    "Unethical behavior"
]

keywords_for_transporation = [
    "Traffic violation",
    "Road safety",
    "Public transportation issues",
    "Infrastructure maintenance",
    "Traffic congestion",
    "Accidents",
    "Parking violations",
    "Road closures",
    "Transportation planning",
    "Pedestrian safety",
    "Bicycle lanes",
    "Public transit delays",
    "Street signage",
    "Road construction",
    "Speed limits",
    "Vehicle emissions",
    "Driver behavior",
    "Public transportation accessibility",
    "Traffic signals",
    "Transportation funding"
]

keywords_for_education = [
    "Education funding",
    "Curriculum standards",
    "Teacher misconduct",
    "Bullying",
    "School safety",
    "Special education services",
    "Discrimination in schools",
    "Textbook quality",
    "Teacher-student relationships",
    "Student discipline",
    "Academic integrity",
    "School facilities maintenance",
    "Educational resources distribution",
    "Access to education",
    "Standardized testing",
    "School bus safety",
    "Extracurricular activities",
    "Parental involvement",
    "Technology in education",
    "Student performance assessment"
]

keywords_for_health = [
    "Healthcare access",
    "Medical malpractice",
    "Patient rights",
    "Healthcare affordability",
    "Public health emergencies",
    "Disease prevention",
    "Healthcare quality",
    "Mental health services",
    "Environmental health hazards",
    "Healthcare insurance",
    "Healthcare fraud",
    "Healthcare provider misconduct",
    "Vaccination policies",
    "Health education programs",
    "Drug safety",
    "Hospital sanitation",
    "Healthcare disparities",
    "Elderly care services",
    "Substance abuse treatment",
    "Nutrition standards"
]

keywords_for_social_services = [
    "Welfare programs",
    "Child protection services",
    "Foster care system",
    "Adoption process",
    "Homelessness assistance",
    "Domestic violence intervention",
    "Elder abuse",
    "Disability services",
    "Food assistance programs",
    "Housing assistance",
    "Social security benefits",
    "Refugee resettlement",
    "Community outreach programs",
    "Substance abuse prevention",
    "Youth programs",
    "Family support services",
    "Financial assistance programs",
    "Job training programs",
    "Immigration services",
    "Legal aid services"
]

keywords_for_environmental_protection = [
    "Pollution control",
    "Air quality",
    "Water contamination",
    "Waste management",
    "Environmental regulations",
    "Endangered species protection",
    "Hazardous waste disposal",
    "Conservation efforts",
    "Environmental impact assessments",
    "Ecological preservation",
    "Renewable energy initiatives",
    "Climate change adaptation",
    "Noise pollution",
    "Soil erosion prevention",
    "Environmental permits",
    "Coastal management",
    "Recycling programs",
    "Green building standards",
    "Environmental justice",
    "Wetland conservation"
]

keywords_for_housing_and_urban_development = [
    "Affordable housing",
    "Homelessness prevention",
    "Housing discrimination",
    "Rental assistance programs",
    "Public housing conditions",
    "Housing subsidies",
    "Urban development projects",
    "Community revitalization",
    "Zoning regulations",
    "Land use planning",
    "Homeownership assistance",
    "Fair housing policies",
    "Eviction prevention",
    "Housing code enforcement",
    "Redevelopment initiatives",
    "Housing finance programs",
    "Sustainable housing practices",
    "Tenant rights",
    "Neighborhood stabilization",
    "Home repair assistance"
]

keywords_for_labor = [
    "Minimum wage laws",
    "Workplace safety regulations",
    "Employment discrimination",
    "Unemployment benefits",
    "Labor union rights",
    "Occupational health standards",
    "Wage theft",
    "Worker's compensation",
    "Workplace harassment",
    "Labor law violations",
    "Job training programs",
    "Equal employment opportunity",
    "Fair labor practices",
    "Family and medical leave",
    "Workforce development",
    "Retirement benefits",
    "Employment contracts",
    "Worker classification",
    "Child labor laws",
    "Employee rights enforcement"
]


keywords_for_agriculture = [
    "Food safety regulations",
    "Agricultural subsidies",
    "Farming practices",
    "Pest control measures",
    "Crop insurance programs",
    "Soil conservation",
    "Livestock welfare",
    "Agricultural research funding",
    "Food labeling standards",
    "Organic certification",
    "Rural development initiatives",
    "Nutrition assistance programs",
    "Farmers markets",
    "Agricultural trade policies",
    "Food supply chain integrity",
    "Aquaculture regulations",
    "Food insecurity initiatives",
    "Agricultural education programs",
    "Agricultural loans and grants",
    "Crop yield forecasting"
]


department_keywords = [
    keywords_for_police,
    keywords_for_transporation,
    keywords_for_education,
    keywords_for_health,
    keywords_for_social_services,
    keywords_for_environmental_protection,
    keywords_for_housing_and_urban_development,
    keywords_for_labor,
    keywords_for_agriculture
]

def get_department_keywords():
    return department_keywords